disk:
  device_groups:
    - defaults:
        randomize_source: /dev/urandom
        readahead_sectors: 256
        nr_requests: 128
      raid_volume: array
      fs_volume: storage
      devices:
        - path: /dev/sda
        - path: /dev/sdb
        - path: /dev/sdc
        - path: /dev/sdd
        - path: /dev/sde
        - path: /dev/sdf
        - path: /dev/sdg
        - path: /dev/sdh

raid:
  mdadm_config:
    device: partitions
    create: owner=root group=disk mode=0660 auto=yes
    homehost: <system>
    mailaddr: root
  speed_limit_min: 1000
  speed_limit_max: 200000
  volumes:
    - name: array
      label: md0
      raid_level: 6
      devices:
        - path: /dev/sda1
        - path: /dev/sdb1
        - path: /dev/sdc1
        - path: /dev/sdd1
        - path: /dev/sde1
        - path: /dev/sdf1
        - path: /dev/sdg1
        - path: /dev/sdh1

crypt:
  defaults:
    cipher: aes-xts-plain64
    key_size: 512
    hash_algorithm: sha512
    iter_time: 5000
  volumes:
    - encrypted_path: /dev/md/array
      decrypted_name: vault

fs:
  volumes:
    - name: storage
      fs_type: ext4
      device_path: /dev/mapper/vault
      mount_location: /mnt/storage

bind:
  read_only:
    - source: /mnt/storage/media-server/library
      target: /exports/library_ro
  read_write:
    - source: /mnt/storage/media-server/library
      target: /exports/library_rw

export:
  host_groups:
    - name: internal_network
      hosts:
        - 192.168.0.0/16
        - 172.16.0.0/12
        - 10.0.0.0/8
    - name: wild
      hosts:
        - "*"
  options:
    - name: read_only
      value: ro,async,crossmnt,no_subtree_check,fsid=0,all_squash
    - name: read_write
      value: rw,sync,crossmnt,no_subtree_check,fsid=0,all_squash
  volumes:
    - path: /exports/library_ro
      host_group_options:
        - host_group: wild
          option: read_only
    - path: /exports/library_rw
      host_group_options:
        - host_group: internal_network
          option: read_write
